---
title: "MrSGUIDE Multiple Responses Subgroup identification using GUIDE"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MrSGUIDE Multiple Responses Subgroup identification}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MrSGUIDE)
```

## Data settings

To illustrate the idea of how `MrS` 

```{r}
set.seed(1234)

N = 300
np = 3

numX <- matrix(rnorm(N * np), N, np)
z <- sample(3, N, replace = TRUE) - 1
gender <- sample(c('Male', 'Female'), N, replace = TRUE)
country <- sample(c('US', 'UK', 'China', 'Japan'), N, replace = TRUE)

y1 <- numX[, 1] + numX[, 2] + 2 * z * (gender == 'Female') + rnorm(N)
y2 <- numX[, 3] + numX[, 1] + 2 * z * (gender == 'Female') + rnorm(N)

train <- data.frame(numX, gender, country, z, y1, y2)
role <- c(rep('n', 3), 'c', 'c', 'r', 'd', 'd')
```

## Fit a MrLin model

```{r}
fit <- MrSFit(dataframe = train, role = role, bestK = 3, 
              maxDepth = 3, CVFolds = 10, CVSE = 0.5, 
              bootNum = 30, alpha = 0.05, display = TRUE, remove=TRUE)
printTree(fit)
```


## Print the result

You can also print details about each node fitting.

```{r}
printTree(fit, details = TRUE, digits = 3)
```

## Plot the tree result

```{r}
plotme <- plotTree(fit)
plotme$treeplot
```

## Plot the treatment effect

```{r, fig.align='center', fig.width=5, fig.height=5}
plotme$trtPlot
```

## Write the tree to Latex

```{r}
writeTex(fit, file = 'test.tex')
```

Follow GUIDE, use `latex`

```{shell}
$ cat test.tex
```

```{r, engine='bash', echo=FALSE, comment=NULL}
cat test.tex
```

```{r, engine='bash', echo=FALSE, comment=NULL}
rm test.tex
```



