# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Charater vector to Interger vector use Rcpp
#'
#' @param x original character vector
#' @param levels the unique value form x, where the index is the output integer vector value
#' @return interger vector
characterToInterger <- function(x, levels) {
    .Call(`_MrS_characterToInterger`, x, levels)
}

#' R dataframe to numeric vector
#'
#' Function will change the original numerical dataframe to a numerical matrix, where missing value will change to Inf.
#'
#' @param numX numerical dataframe
#' @return numerical matrix
dataFramToNumeric <- function(numX) {
    .Call(`_MrS_dataFramToNumeric`, numX)
}

#' Character or factor dataframe change to integer matrix.
#'
#' Character dataframe, for each column, use \code{characterToInteger()} with unique value from character vector
#'
#' @param charX character dataframe or factor dataframe
#' @param levels, the desired levels for each character vector
#'
#' @return list intX the integer matrix x, with crosspoding levels.
#'
characterDict <- function(charX, levels) {
    .Call(`_MrS_characterDict`, charX, levels)
}

#' Multiple response subgroup identification use GUIDE Gi option with step wise regression
#'
GiStepWisePure <- function(numX, catX, Y, trt, splitIndex, fitIndex, holdIndex, bestK, maxDepth, minData, minTrt, batchNum, CVFold, CVSE, bootNum, alpha, faster, display, varName, treeName, nodeName, bootName) {
    invisible(.Call(`_MrS_GiStepWisePure`, numX, catX, Y, trt, splitIndex, fitIndex, holdIndex, bestK, maxDepth, minData, minTrt, batchNum, CVFold, CVSE, bootNum, alpha, faster, display, varName, treeName, nodeName, bootName))
}

