# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

characterToInterger <- function(x, levels) {
    .Call(`_Mr_S_characterToInterger`, x, levels)
}

dataFramToNumeric <- function(numX) {
    .Call(`_Mr_S_dataFramToNumeric`, numX)
}

characterDict <- function(charX, levels) {
    .Call(`_Mr_S_characterDict`, charX, levels)
}

initLog <- function(level) {
    invisible(.Call(`_Mr_S_initLog`, level))
}

GiStepWisePure <- function(numX, catX, Y, trt, splitIndex, fitIndex, holdIndex, bestK, maxDepth, minData, minTrt, batchNum, CVFold, CVSE, bootNum, alpha, faster, display, varName, treeName, nodeName, bootName) {
    invisible(.Call(`_Mr_S_GiStepWisePure`, numX, catX, Y, trt, splitIndex, fitIndex, holdIndex, bestK, maxDepth, minData, minTrt, batchNum, CVFold, CVSE, bootNum, alpha, faster, display, varName, treeName, nodeName, bootName))
}

